web:
    image: rubberbullet/phalcon
    volumes:
        - ../../../../upload-service:/var/www/service
        - ./default.conf:/etc/nginx/sites-enabled/default.conf
    ports:
        - "8094:80"
    links:
        - db
        - redis
    working_dir: /var/www/service

db:
    image: rubberbullet/mariadb
    volumes:
        - /data/image/db/:/var/lib/mysql
    ports:
        - "3376:3306"

redis:
  image: rubberbullet/redis
  volumes:
    - /data/redis/image/:/data
  ports:
    - "6880:6380"
