<html>
    <head>
        <title>Upload Image</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <style>
            .fileUpload {
                position: relative;
                overflow: hidden;
                margin: 10px;
            }
            .fileUpload input.image {
                position: absolute;
                top: 0;
                right: 0;
                margin: 0;
                padding: 0;
                font-size: 20px;
                cursor: pointer;
                opacity: 0;
                filter: alpha(opacity=0);
            }
            .form {
                position: absolute;
                top: 200px;
                left: 450px;
            }
            .uploadFile {
                width: 300px;
            }

            input#uploadBtn{
                cursor:pointer;
                padding:5px 25px;
                background:#35b128;
                border:1px solid #33842a;
                -moz-border-radius: 10px;
                -webkit-border-radius: 10px;
                border-radius: 10px;
                -webkit-box-shadow: 0 0 4px rgba(0,0,0, .75);
                -moz-box-shadow: 0 0 4px rgba(0,0,0, .75);
                box-shadow: 0 0 4px rgba(0,0,0, .75);
                color:#f3f3f3;
                font-size:1.1em;
            }

            input#uploadBtn:hover, input#uploadBtn:focus{
                background-color :#399630;
                -webkit-box-shadow: 0 0 1px rgba(0,0,0, .75);
                -moz-box-shadow: 0 0 1px rgba(0,0,0, .75);
                box-shadow: 0 0 1px rgba(0,0,0, .75);
            }
            .upDiv{
                position: relative;
                font-size: 16px;
                font-weight: 700;
                top: 150px;
                left: 120px;
            }
        </style>
    </head>
    <body>
        <form enctype="multipart/form-data" action="/upload" method="post" name="upload form" class="form" id="form">
            <input id="uploadFile" class="uploadFile" placeholder="Choose Image" disabled="disabled" />
            <div class="fileUpload btn btn-primary">
                <span>Meesho Image</span>
                <input id="imageBtn" type="file" class="image" name="image" />
            </div>
            </br>
            <div class="upDiv">
                <input id="uploadBtn" type="button" class="upload" value="Upload" onclick="upload()"/>
            </div>
        </form>
    </body>
    <script>
        $("#imageBtn").on("change", function () {
            var file = this.value;
            var formData = new FormData();
            formData.append("image", $("#imageBtn")[0].files[0]);
            $("#uploadFile").val(file.split('\\').pop());
            $.ajax({
                type: "POST",
                url: "/upload",
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    alert("Success");
                }
            });
        });
        function upload() {
        }
    </script>
</html>
