<html>
    <head>
        <title>Upload Image</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <style>
            .fileUpload {
                position: relative;
                overflow: hidden;
                margin: 10px;
            }
            .fileUpload input.image {
                position: absolute;
                top: 0;
                right: 0;
                margin: 0;
                padding: 0;
                font-size: 20px;
                cursor: pointer;
                opacity: 0;
                filter: alpha(opacity=0);
            }
            .form {
                position: absolute;
                top: 200px;
                left: 450px;
            }
            .uploadFile {
                width: 300px;
            }

            input#uploadBtn{
                cursor:pointer;
                padding:5px 25px;
                background:#35b128;
                border:1px solid #33842a;
                -moz-border-radius: 10px;
                -webkit-border-radius: 10px;
                border-radius: 10px;
                -webkit-box-shadow: 0 0 4px rgba(0,0,0, .75);
                -moz-box-shadow: 0 0 4px rgba(0,0,0, .75);
                box-shadow: 0 0 4px rgba(0,0,0, .75);
                color:#f3f3f3;
                font-size:1.1em;
            }

            input#uploadBtn:hover, input#uploadBtn:focus{
                background-color :#399630;
                -webkit-box-shadow: 0 0 1px rgba(0,0,0, .75);
                -moz-box-shadow: 0 0 1px rgba(0,0,0, .75);
                box-shadow: 0 0 1px rgba(0,0,0, .75);
            }
            .upDiv{
                position: relative;
                font-size: 16px;
                font-weight: 700;
                top: 150px;
                left: 120px;
            }
            .msg{
                position: absolute;
                font-weight: 400;
                top: -65px;
                left: 100px;
            }
            .green{
                color: #006600;
            }
            .red{
                color: #ff0000;
            }
        </style>
    </head>
    <body>
        <form enctype="multipart/form-data" action="/upload" method="post" name="upload form" class="form" id="form">
            <p id="msg" class="msg"></p>
            <input id="uploadFile" class="uploadFile" placeholder="Choose Image" disabled="disabled" />
            <div class="fileUpload btn btn-primary">
                <span>Meesho Image</span>
                <input id="imageBtn" type="file" class="image" name="image" />
            </div>
            </br>
            <div class="upDiv">
                <input id="uploadBtn" type="button" class="upload" value="Upload Image" onclick="upload()"/>
            </div>
            <input type="hidden" id="key" name="key" value="">
        </form>
    </body>
    <script>
        $("#imageBtn").on("change", function () {
            var file = this.value;
            var formData = new FormData();
            formData.append("image", $("#imageBtn")[0].files[0]);
            $("#uploadFile").val(file.split('\\').pop());
            $.ajax({
                type: "POST",
                url: "/upload",
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    var json = $.parseJSON(data);
                    if (json.success === true && $.trim(json.error) === "") {
                        $('#key').val(json.key);
                        $("#msg").addClass("green").removeClass("red").text("");
                    } else {
                        $("#msg").addClass("red").removeClass("green").text(json.error);
                    }
                }
            });
        });
        function upload() {
            if (validateUpload() == false) {
                $("#msg").addClass("red").removeClass("green");
                return false;
            }
            var formData = new FormData();
            $key = $('#key').val();
            formData.append('key', $key);
            $.ajax({
                type: "POST",
                url: "/save",
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function (data) {
                    var json = $.parseJSON(data);
                    if (json.success === true) {
                        $('#key').val('');
                        $("#msg").addClass("green").removeClass("red").text("Uploaded Image Successfully");
                    } else {
                        $("#msg").addClass("red").removeClass("green").text(json.error);
                    }
                }
            });
        }
        function validateUpload() {
            if ($.trim($("#uploadFile").val()) == '') {
                $("#msg").text("Please choose an Image !!!");
                return false;
            } else if ($.trim($("#key").val()) == '') {
                $("#msg").text("Some error occurred. Please choose Image again !!!");
                return false;
            }
            return true;
        }
    </script>
</html>
